from .clip_templates import (IMAGENET_TEMPLATES, IMAGENET_TEMPLATES_SELECT,
                             IMAGENET_TEMPLATES_SELECT_CLIP, ViLD_templates)

__all__ = [
    'IMAGENET_TEMPLATES', 'IMAGENET_TEMPLATES_SELECT',
    'IMAGENET_TEMPLATES_SELECT_CLIP', 'ViLD_templates'
]
