#!/bin/bash
#SBATCH --partition gmai
#SBATCH --quotatype spot
#SBATCH --gres gpu:1
#SBATCH --cpus-per-task 16
#SBATCH -o phoenix-slurm-%j.out
# args: -p
# args: gmai
# args: --quotatype=spot
# args: --gres=gpu:1
# args: --cpus-per-task=16
# args: mim
# args: train
# args: mmseg
# args: ./configs/fcn-unet-s5-d16_unet_1xb16-0.01-20k_bactteria-detection-512x512.py
# args: auto_resume=True
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
