"""
Sen1Floods11 fine-tune: S1Hand (2-band VV/VH SAR).

Expected on-disk layout (see tools/setup_sen1floods11.py)::

    data/Sen1Floods11/
        S1Hand/<base>_S1Hand.tif       # 2-band SAR (VV, VH in dB)
        S2Hand/<base>_S2Hand.tif       # 13-band Sentinel-2 MSI (unused here)
        LabelHand/<base>_LabelHand.tif # 1-band label: -1=nodata, 0=bg, 1=flood
        splits/train.txt               # one <base> per line, generated by
        splits/val.txt                 # tools/setup_sen1floods11.py
        splits/test.txt

All tiles are 512x512. Labels are signed TIFFs; the ``-1`` nodata
value is remapped to ``ignore_index=255`` by
:class:`LoadSen1Floods11Annotation`.

Setup (run once, before the first training run):

    # 1. Generate train/val/test splits + compute mean/std for s1 & s2.
    python tools/setup_sen1floods11.py --data-root data/Sen1Floods11

    # 2. Paste the printed NORM_CONFIGS block into the 's1' entry in
    #    mmseg/datasets/transforms/multimodal_pipelines.py
    #    (skip this if you're happy with the shipped defaults).

Training:

    python tools/train.py configs/floodnet/finetune_sen1floods11_s1.py \\
        --work-dir work_dirs/generalization/sen1floods11_s1/ \\
        --cfg-options \\
            load_from="work_dirs/floodnet/SwinmoeB/655/best_mIoU_epoch_100.pth"

The pretrained Swin-Base + MoE checkpoint has modal-specific patch
embeds / decode heads for ``sar / rgb / GF``. Here we redefine the
single trainable modal as ``s1`` (2-channel) and the single decode-head
key as ``s1``; the mismatched pretrained keys are ignored on load
(``strict=False``), so the new patch-embed and decode head train from
scratch while the frozen Swin stages reuse their pretrained weights.
"""

_base_ = ['./finetune_stem_decoder.py']

# ==================== Modal / dataset identifiers ====================
MODAL_NAME = 's1'
MODAL_CHANNELS = 2

ALL_KNOWN_MODALS = {
    # _delete_ forces a full replacement so the base config's
    # sar/rgb/GF entries don't leak through.
    '_delete_': True,
    MODAL_NAME: {
        'channels': MODAL_CHANNELS,
        'pattern': 's1hand',
        'description': 'Sen1Floods11 S1Hand (VV/VH dB)',
    },
}
TRAINING_MODALS = [MODAL_NAME]
DATASET_NAMES = [MODAL_NAME]

# 512x512 input -> crop to 256x256 for training (gives ~4x position
# diversity per tile and keeps each training step cheap).
crop_size = (256, 256)

# ==================== Model override ====================
model = dict(
    dataset_names=DATASET_NAMES,
    backbone=dict(
        modal_configs=ALL_KNOWN_MODALS,
        training_modals=TRAINING_MODALS,
        # frozen_stages / freeze_patch_embed inherit from base
    ),
)

# ==================== Dataset / pipelines ====================
dataset_type = 'Sen1Floods11Dataset'
data_root = 'data/Sen1Floods11/'

# All tiles are already 512x512, so no RandomResize is needed.
# Pipeline order:
#   1. Load image (sets 'img')
#   2. Load annotation (sets 'gt_seg_map', 'seg_fields')
#      - must come BEFORE RandomCrop so cat_max_ratio can check label
#        distribution and avoid degenerate all-background crops.
#   3. RandomCrop 256x256
#   4. RandomFlip
#   5. MultiModalNormalize (NaN/Inf-safe, modality-aware mean/std)
#   6. MultiModalPad to crop_size (no-op if RandomCrop matched exactly,
#      but handles any edge case where the tile is <crop_size).
#   7. PackMultiModalSegInputs -> SegDataSample
train_pipeline = [
    dict(type='LoadMultiModalImageFromFile', to_float32=True),
    dict(type='LoadSen1Floods11Annotation'),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='MultiModalNormalize'),
    dict(type='MultiModalPad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='PackMultiModalSegInputs',
         meta_keys=('img_path', 'ori_filename', 'ori_shape', 'img_shape',
                    'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                    'modal_type', 'actual_channels', 'dataset_name',
                    'img_norm_cfg', 'reduce_zero_label')),
]

# Test / val: feed the full 512x512 tile; sliding-window inference
# (configured in the base config as mode='slide', crop_size=256,
# stride=170) handles the cropping internally.
test_pipeline = [
    dict(type='LoadMultiModalImageFromFile', to_float32=True),
    dict(type='LoadSen1Floods11Annotation'),
    dict(type='MultiModalNormalize'),
    dict(type='PackMultiModalSegInputs',
         meta_keys=('img_path', 'ori_filename', 'ori_shape', 'img_shape',
                    'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                    'modal_type', 'actual_channels', 'dataset_name',
                    'img_norm_cfg', 'reduce_zero_label')),
]

# ==================== Dataloaders ====================
# _delete_=True on sampler forces full replacement so the base
# FixedRatioModalSampler config is discarded - Sen1Floods11 is single
# modal, so we just use the standard shuffling sampler.
#
# ann_file='splits/train.txt' is resolved relative to data_root by
# BaseSegDataset._join_prefix, so the actual path read is
# data/Sen1Floods11/splits/train.txt . Generate these files with
# tools/setup_sen1floods11.py before training.
train_dataloader = dict(
    batch_size=16,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(
        _delete_=True,
        type='DefaultSampler',
        shuffle=True,
    ),
    dataset=dict(
        _delete_=True,
        type=dataset_type,
        data_root=data_root,
        modality=MODAL_NAME,
        ann_file='splits/train.txt',
        data_prefix=dict(
            img_path='S1Hand',
            seg_map_path='LabelHand',
        ),
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        _delete_=True,
        type=dataset_type,
        data_root=data_root,
        modality=MODAL_NAME,
        ann_file='splits/val.txt',
        data_prefix=dict(
            img_path='S1Hand',
            seg_map_path='LabelHand',
        ),
        pipeline=test_pipeline,
    ),
)

test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        _delete_=True,
        type=dataset_type,
        data_root=data_root,
        modality=MODAL_NAME,
        ann_file='splits/test.txt',
        data_prefix=dict(
            img_path='S1Hand',
            seg_map_path='LabelHand',
        ),
        pipeline=test_pipeline,
    ),
)
